### ISSUE TITLE
OH2 Local Install Broken against Cloud Instance

### ISSUE THREAD

**Issue by APorterCSUMB** [CSUMB-SP17-CST499/MYBUTLER#7]
The local install of OH2 on the RPi was unable to call out to the OHCloud instance from the Networking Lab in BIT. This MUST be resolved, as our final server will be an RPi and the demo will be inside BIT using their networking scheme.

- [x] Spin Up RPi with Full, Clean Jessie Image 
- [x] Use install scripts to create OH2 environment #8 
- [x] Spin up cloud VM with clean Ubuntu install
- [x] Use install scripts to create OHCloud environment #11 
- [x] Sign up for account on new OHCloud, and mongodump the db to get code #11 
- [x] Configure OHCloud with DNS name and firewall exclusions and UUID/secret
- [x] Configure OH2Local with DNS name of OHCloud
- [x] Ensure the two instances can talk
- [x] Second Member Agrees

**Comment by APorterCSUMB** [comment]
Ok, solved. Second person must follow scripting setup and verify but I believe this is ok, moving forward. Also pushed #14 in order to help with RPi aspect.

**Comment by APorterCSUMB** [comment]
@dw1lson verified connection between his cloud and local instance. OK to approve PR any time.
